GET http://localhost:9000 HTTP/1.1
content-type: application/json

{
    "type":"message_new",
    "object":{
        "date":1565426994,
        "from_id":122292089,
        "id":2506,
        "out":0,
        "peer_id":122292089,
        "text":"list",
        "conversation_message_id":2340,
        "fwd_messages":[],
        "important":false,
        "random_id":0,
        "attachments":[],
        "payload":"{\"button\":\"3\"}",
        "is_hidden":false
        },
    "group_id":54136463,
    "secret":"secretKey"
}