name: deploy
on:
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v1
      with:
        go-version: 1.14
    - uses: actions/checkout@v1
      
    - name: install golangci-lint
      run: curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.21.0

    - name: golangci-lint
      run: $(go env GOPATH)/bin/golangci-lint run

    - uses: docker/build-push-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: delgus/jokebot
        tags: latest
      
    - uses: appleboy/ssh-action@v0.0.9
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        password: ${{ secrets.PSW }}
        script: | 
          docker run --name=jokebot --rm -e VK_ACCESS_TOKEN=${{ secrets.VK_ACCESS_TOKEN }} -e VK_CONFIRM_TOKEN=${{ secrets.VK_CONFIRM_TOKEN }} -e VK_SECRET_KEY=${{ secrets.VK_SECRET_KEY }} -e DB_DRIVER=${{ secrets.DB_DRIVER }} -e DB_ADDR=${{ secrets.DB_ADDR }} -e TG_ACCESS_TOKEN=${{ secrets.TG_ACCESS_TOKEN }} -e TG_WEBHOOK=${{ secrets.TG_WEBHOOK}} -p ${{ secrets.DEPLOY_PORT }}:80 delgus/jokebot

