name: deploy
on:
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: 1.14
        
    - uses: actions/checkout@v2
      
    - uses: golangci/golangci-lint-action@v1
      with:
          version: v1.27
    
    - name: build 
      run: CGO_ENABLED=0 make build

    - uses: docker/build-push-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: delgus/jokebot
        tags: latest
      
    - uses: sagebind/docker-swarm-deploy-action@v2
      with:
        remote_host: tcp://${{ secrets.HOST }}:2376
        args: stack deploy -c deploy.yml jokebot
      env:
        TG_ACCESS_TOKEN: ${{ secrets.TG_ACCESS_TOKEN }}
        TG_WEBHOOK: ${{ secrets.TG_WEBHOOK}}
        VK_ACCESS_TOKEN: ${{ secrets.VK_ACCESS_TOKEN }}
        VK_CONFIRM_TOKEN: ${{ secrets.VK_CONFIRM_TOKEN }}
        VK_SECRET_KEY: ${{ secrets.VK_SECRET_KEY }}
        DB_DRIVER: ${{ secrets.DB_DRIVER }}
        DB_ADDR: ${{ secrets.DB_ADDR }}
        DEPLOY_PORT: ${{ secrets.DEPLOY_PORT }}
        LOG_TG_CHAT_ID: ${{ secrets.LOG_TG_CHAT_ID }}
        LOG_TG_ACCESS_TOKEN: ${{ secrets.LOG_TG_ACCESS_TOKEN }}
          
